#!/bin/python3

"""

local/bin/medaf

-------------------------------

This file is MEDAF's CLI tool. This file will be added into your PATH. Simple as that.

-------------------------------

Copyright (C) 2022, Anokidev. All right reserved. 
Medaf is licensed in MIT License, see ./LICENSE.md for more info.

"""

import sys
import os
import importlib.util

HELP = r"""
Medaf help:

All "commands" are actually apps CLI. There are bundled
apps such as: project, plugin, help, and version.

Basically:

medaf [APP NAME] [COMMAND NAME] [SUBCOMMAND NAME]

project:
    - init [PROJECT NAME] : Initialize a new project.
        - "--template=[TEMPLATE]" : Insert template.
    - run [APP NAME] : Run an app INSIDE your project.
        - "--debug=[true, false]" : Enable debug mode.

plugin:
    - install [PLUGIN NAME] : Install and register a plugin.
    - remove [PLUGIN NAME] : Remove a plugin.

help / --help / -h:
    - [NO SUBCOMMAND] : Show this.

version / --version / -v:
    - [NO SUBCOMMAND] : Show version.
    - credits : Show credits.
    - changelogs : Show changelogs.
    - license : Show license."""

if __name__ == "__main__":

    # Arguments.
    args: list = sys.argv[1:]

    # Import project.py
    spec = importlib.util.spec_from_file_location("a", f"{os.cwd()}/project.py")
    project_config = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(project_config)
    
    # Get all the configurations.
    local_content_apps: dict    = project_config.LOCAL_CONTENT_APPS
    local_middleware_apps: list = project_config.LOCAL_MIDDLEWARE_APPS
    local_gateway_apps: list    = project_config.LOCAL_GATEWAY_APPS
    plugin_apps: dict           = project_config.PLUGIN_APPS

    # Ge

